# Generated by Django 5.2.12 on 2026-04-05 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='+998 xx xxx xx xx formatida kiriting', regex='^\\+998\\d{9}$')]),
        ),
    ]
