# Generated by Django 5.2.12 on 2026-04-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_slug'),
        ('users', '0004_sellerprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catgories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.sellerprofile'),
            preserve_default=False,
        ),
    ]
