# Generated by Django 5.2.12 on 2026-04-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_sellerprofile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='catalog/')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Canceled'), ('completed', 'Completed')], default='pending')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile')),
            ],
        ),
    ]
