# Generated by Django 5.2.12 on 2026-04-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequest',
            name='comment',
            field=models.CharField(default='sawodiawd', max_length=500),
            preserve_default=False,
        ),
    ]
