# Generated by Django 5.2.12 on 2026-04-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_categoryrequest_comment'),
        ('users', '0004_sellerprofile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_request', to='users.sellerprofile'),
        ),
    ]
