# Generated by Django 5.2.12 on 2026-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_categoryrequest_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequest',
            name='cancelled_by_role',
            field=models.CharField(blank=True, default='seller', null=True),
        ),
    ]
